### ISSUE TITLE
Reeder.app is unable to find RSS feed

### ISSUE THREAD

**Issue by Tanner** [jezen/jezenthomas.com#3]
[Reeder](https://reederapp.com/) on iOS is unable to find your RSS feed when just entering `https://jezenthomas.com/` in the URL prompt.

I couldn’t find a documented list of URL’s that Reeder looks for, but perhaps `rss.xml`?

**Comment by Tanner** [comment]
Alternatively, maybe just link to your RSS feed in your navigation or in your blog’s footer.

**Comment by vincentbernat** [comment]
I was also looking for the RSS feed. It's available as `/feed.xml`, but without looking at the source, I don't see how people would discover that! :)
